import {
  BusinessTenant,
  Sale,
  Expense,
  Invoice,
  Customer,
  ProductItem,
  Supplier,
  ComplianceTask,
  NewsArticle,
  TrainingCourse,
  Opportunity,
  WhatsAppTemplate,
  WhatsAppConversation,
} from '../types';

export const DEMO_TENANT: BusinessTenant = {
  id: 'demo-mama-njeri',
  name: 'Mama Njeri Supplies',
  ownerName: 'Grace Njeri Mwangi',
  email: 'njeri.supplies@bizhubke.demo',
  phone: '+254 722 849 120',
  county: 'Nairobi',
  businessType: 'Wholesale',
  employeeCount: '4 - 10',
  monthlySalesRange: 'KSh 300,000 - KSh 1,000,000',
  plan: 'Business',
  trialDaysLeft: 5,
  lowCashThreshold: 50000,
  challenges: ['Cash flow', 'Managing stock', 'Tax/compliance', 'Customer retention'],
  createdAt: '2026-01-15',
  isDemo: true,
};

export const DEMO_SALES: Sale[] = [
  {
    id: 'sale-001',
    date: '2026-09-21',
    customerName: 'Kiprono Hotel & Bakery',
    productOrService: 'Golden Fry Cooking Oil (20L Jerrycan x 4)',
    category: 'Cooking Oil & Fats',
    quantity: 4,
    amount: 24800,
    paymentMethod: 'M-Pesa',
    reference: 'QKD8291NJL',
    notes: 'Delivered to Ronald Ngala Street branch',
  },
  {
    id: 'sale-002',
    date: '2026-09-20',
    customerName: 'Amina Mini Market (Eastleigh)',
    productOrService: 'Pishori Rice Grade 1 (50kg Bag x 3)',
    category: 'Grains & Cereals',
    quantity: 3,
    amount: 21600,
    paymentMethod: 'M-Pesa',
    reference: 'QKD7104HJM',
    notes: 'Paid via Till 892341',
  },
  {
    id: 'sale-003',
    date: '2026-09-19',
    customerName: 'Westlands Fast Foods',
    productOrService: 'Ajab Fortified Wheat Flour (12x2kg bale x 10)',
    category: 'Flour & Baking',
    quantity: 10,
    amount: 19500,
    paymentMethod: 'Bank Transfer',
    reference: 'EFT-NCBA-9912',
    notes: 'Bi-weekly scheduled bakery order',
  },
  {
    id: 'sale-004',
    date: '2026-09-18',
    customerName: 'Balozi Retailers (South C)',
    productOrService: 'Sunlight Washing Powder & Bar Soap carton',
    category: 'Soaps & Detergents',
    quantity: 8,
    amount: 18400,
    paymentMethod: 'M-Pesa',
    reference: 'QKC6294PPK',
    notes: 'Walk-in cash & carry order',
  },
  {
    id: 'sale-005',
    date: '2026-09-17',
    customerName: 'Corner Store Ngara',
    productOrService: 'Assorted Sugar 50kg & Salt bags',
    category: 'Dry Goods',
    quantity: 5,
    amount: 32000,
    paymentMethod: 'Cash',
    reference: 'CSH-9810',
    notes: 'Collected directly at warehouse',
  },
  {
    id: 'sale-006',
    date: '2026-09-15',
    customerName: 'Highridge Canteen',
    productOrService: 'Royco & Spices Assortment Bundle',
    category: 'Spices & Condiments',
    quantity: 12,
    amount: 14200,
    paymentMethod: 'M-Pesa',
    reference: 'QKB4019LPA',
  },
  {
    id: 'sale-007',
    date: '2026-09-12',
    customerName: 'Kiprono Hotel & Bakery',
    productOrService: 'Premium Baking Flour (50kg bag x 6)',
    category: 'Flour & Baking',
    quantity: 6,
    amount: 34500,
    paymentMethod: 'M-Pesa',
    reference: 'QKA1948BTY',
  },
  {
    id: 'sale-008',
    date: '2026-09-08',
    customerName: 'St. Teresa School Board',
    productOrService: 'Term 3 Grain Supply (Rice, Beans, Maize)',
    category: 'Grains & Cereals',
    quantity: 20,
    amount: 165000,
    paymentMethod: 'Bank Transfer',
    reference: 'KCB-TR-77189',
    notes: 'Half payment received, remainder on 30-day invoice',
  },
  {
    id: 'sale-009',
    date: '2026-09-04',
    customerName: 'Zainab Superette',
    productOrService: 'Pure Highland Tea 500g (Catering packs)',
    category: 'Beverages',
    quantity: 15,
    amount: 28500,
    paymentMethod: 'M-Pesa',
    reference: 'QK981729XX',
  },
  {
    id: 'sale-010',
    date: '2026-08-28',
    customerName: 'Various Walk-in Counter Sales',
    productOrService: 'General Retail Replenishment Packs',
    category: 'Dry Goods',
    quantity: 35,
    amount: 124000,
    paymentMethod: 'M-Pesa',
    reference: 'MPESA-SUM-AUG',
  },
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    date: '2026-09-18',
    category: 'Stock',
    payee: 'Bidco Africa Ltd Distributor',
    amount: 185000,
    paymentMethod: 'Bank Transfer',
    notes: 'Bulk purchase: Golden Fry cooking oil & Kimbo',
    hasReceipt: true,
  },
  {
    id: 'exp-002',
    date: '2026-09-15',
    category: 'Rent',
    payee: 'Nyayo Plaza Management Co.',
    amount: 55000,
    paymentMethod: 'Bank Transfer',
    notes: 'Warehouse Unit 4B - September 2026',
    hasReceipt: true,
  },
  {
    id: 'exp-003',
    date: '2026-09-14',
    category: 'Salaries',
    payee: 'Store Clerk & Loader casuals (4 staff)',
    amount: 48000,
    paymentMethod: 'M-Pesa',
    notes: 'Bi-monthly payroll disbursements via M-Pesa B2C',
    hasReceipt: true,
  },
  {
    id: 'exp-004',
    date: '2026-09-12',
    category: 'Transport',
    payee: 'Beba Beba Trucking Logistics',
    amount: 22500,
    paymentMethod: 'M-Pesa',
    notes: 'Deliveries to Eastleigh, Westlands, and South C',
    hasReceipt: true,
  },
  {
    id: 'exp-005',
    date: '2026-09-08',
    category: 'Utilities',
    payee: 'Kenya Power (KPLC Prepaid)',
    amount: 11200,
    paymentMethod: 'M-Pesa',
    notes: 'Meter #37194012 token purchase',
    hasReceipt: true,
  },
  {
    id: 'exp-006',
    date: '2026-09-05',
    category: 'Taxes',
    payee: 'Kenya Revenue Authority (KRA)',
    amount: 18450,
    paymentMethod: 'Bank Transfer',
    notes: 'August VAT payment on eTIMS PRN 8920192',
    hasReceipt: true,
  },
  {
    id: 'exp-007',
    date: '2026-09-03',
    category: 'Marketing',
    payee: 'SMS Gateway Kenya Ltd',
    amount: 4500,
    paymentMethod: 'M-Pesa',
    notes: 'Bulk promotional SMS to 1,200 retail store owners',
    hasReceipt: true,
  },
  {
    id: 'exp-008',
    date: '2026-09-01',
    category: 'Bank charges',
    payee: 'Equity Bank & Safaricom Till Fees',
    amount: 9420,
    paymentMethod: 'Bank Transfer',
    notes: 'Monthly merchant settlement charges',
    hasReceipt: false,
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-0048',
    customerName: 'St. Teresa School Board',
    customerEmail: 'accounts@stteresaschool.ac.ke',
    customerPhone: '+254 733 910 200',
    issueDate: '2026-09-08',
    dueDate: '2026-10-08',
    status: 'Unpaid',
    items: [
      { id: '1', description: 'Grade 1 Long Grain Pishori (50kg x 10)', quantity: 10, unitPrice: 7200, taxRate: 0 },
      { id: '2', description: 'Dry Yellow Beans (50kg x 5)', quantity: 5, unitPrice: 6500, taxRate: 0 },
    ],
    subtotal: 104500,
    taxTotal: 0,
    total: 104500,
    notes: 'Payment by Cheque or KCB Paybill 522522 Acc: MAMANJERI',
    paymentInstructions: 'M-Pesa Paybill: 400200 | Acc No: 011092849102 | Equity Bank Westlands',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-0049',
    customerName: 'Safari Club Catering Services',
    customerEmail: 'procurement@safariclub.co.ke',
    customerPhone: '+254 721 445 110',
    issueDate: '2026-08-25',
    dueDate: '2026-09-15',
    status: 'Overdue',
    items: [
      { id: '1', description: 'Assorted Premium Basmati Rice (25kg x 12)', quantity: 12, unitPrice: 4500, taxRate: 0 },
      { id: '2', description: 'Golden Fry Cooking Oil 20L x 5', quantity: 5, unitPrice: 6200, taxRate: 0 },
    ],
    subtotal: 74000,
    taxTotal: 0,
    total: 74000,
    notes: 'Kindly clear this outstanding overdue balance',
    paymentInstructions: 'M-Pesa Till: 892341 (Mama Njeri Supplies)',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-0045',
    customerName: 'Westlands Fast Foods',
    customerEmail: 'westlandsfastfoods@gmail.com',
    customerPhone: '+254 720 334 556',
    issueDate: '2026-09-01',
    dueDate: '2026-09-15',
    status: 'Paid',
    items: [
      { id: '1', description: 'Ajab Bakers Flour 50kg x 8', quantity: 8, unitPrice: 4200, taxRate: 0 },
    ],
    subtotal: 33600,
    taxTotal: 0,
    total: 33600,
    notes: 'Paid in full on 14th Sept via M-Pesa',
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-01',
    name: 'Kiprono Hotel & Bakery',
    phone: '+254 722 411 902',
    email: 'info@kipronohotel.co.ke',
    location: 'Nairobi CBD (Ronald Ngala)',
    type: 'Corporate',
    tags: ['VIP', 'Repeat Customer'],
    totalSpent: 342000,
    ordersCount: 24,
    lastPurchaseDate: '2026-09-21',
    notes: 'Consistently orders flour and oil weekly. Pays on delivery.',
  },
  {
    id: 'cust-02',
    name: 'Amina Mini Market',
    phone: '+254 710 882 390',
    email: 'amina.market@gmail.com',
    location: 'Eastleigh Section 3',
    type: 'Wholesale',
    tags: ['Repeat Customer', 'Wholesale'],
    totalSpent: 188500,
    ordersCount: 16,
    lastPurchaseDate: '2026-09-20',
    notes: 'Prefers morning deliveries before 10 AM to beat traffic.',
  },
  {
    id: 'cust-03',
    name: 'St. Teresa School Board',
    phone: '+254 733 910 200',
    email: 'accounts@stteresaschool.ac.ke',
    location: 'Parklands, Nairobi',
    type: 'Corporate',
    tags: ['VIP'],
    totalSpent: 410000,
    ordersCount: 6,
    lastPurchaseDate: '2026-09-08',
    notes: 'Large termly grain orders. 30-day payment term.',
  },
  {
    id: 'cust-04',
    name: 'Westlands Fast Foods',
    phone: '+254 720 334 556',
    email: 'westlandsfastfoods@gmail.com',
    location: 'Mpaka Road, Westlands',
    type: 'Wholesale',
    tags: ['Repeat Customer'],
    totalSpent: 96400,
    ordersCount: 9,
    lastPurchaseDate: '2026-09-19',
    notes: 'Ordered 10 bales Ajab flour.',
  },
  {
    id: 'cust-05',
    name: 'Balozi Retailers',
    phone: '+254 724 990 123',
    email: 'balozi.southc@yahoo.com',
    location: 'South C Shopping Mall',
    type: 'Retail',
    tags: ['New'],
    totalSpent: 38400,
    ordersCount: 2,
    lastPurchaseDate: '2026-09-18',
    notes: 'Onboarded via WhatsApp broadcast promotion.',
  },
  {
    id: 'cust-06',
    name: 'Mama Zawadi Dukawala',
    phone: '+254 712 003 445',
    email: '',
    location: 'Gikomba Market Gate 2',
    type: 'Retail',
    tags: ['Inactive'],
    totalSpent: 45000,
    ordersCount: 4,
    lastPurchaseDate: '2026-06-15',
    notes: 'Has not ordered in 90 days. Ideal candidate for reactivation message.',
  },
];

export const DEMO_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-01',
    name: 'Golden Fry Vegetable Cooking Oil (20L)',
    sku: 'OIL-GF-20L',
    category: 'Cooking Oil & Fats',
    purchasePrice: 5600,
    sellingPrice: 6200,
    quantity: 42,
    minStockLevel: 15,
    supplier: 'Bidco Africa Ltd Distributor',
    location: 'Warehouse Bay A1',
    status: 'Healthy',
  },
  {
    id: 'prod-02',
    name: 'Mwea Grade 1 Pishori Rice (50kg Bag)',
    sku: 'RCE-PISH-50K',
    category: 'Grains & Cereals',
    purchasePrice: 6400,
    sellingPrice: 7200,
    quantity: 18,
    minStockLevel: 25,
    supplier: 'Kirinyaga Millers Coop',
    location: 'Bay B2',
    status: 'Low',
  },
  {
    id: 'prod-03',
    name: 'Ajab Bakers Wheat Flour (50kg)',
    sku: 'FLR-AJAB-50K',
    category: 'Flour & Baking',
    purchasePrice: 3800,
    sellingPrice: 4350,
    quantity: 8,
    minStockLevel: 20,
    supplier: 'Grain Bulk Millers',
    location: 'Bay C1',
    status: 'Critical',
  },
  {
    id: 'prod-04',
    name: 'Ndengu / Green Grams Special (50kg)',
    sku: 'PLSE-NDG-50K',
    category: 'Grains & Cereals',
    purchasePrice: 7800,
    sellingPrice: 9100,
    quantity: 34,
    minStockLevel: 10,
    supplier: 'Machakos Agro Traders',
    location: 'Bay B3',
    status: 'Healthy',
  },
  {
    id: 'prod-05',
    name: 'Brown Sugar Kilombero (50kg Bag)',
    sku: 'SGR-KIL-50K',
    category: 'Dry Goods',
    purchasePrice: 5900,
    sellingPrice: 6600,
    quantity: 26,
    minStockLevel: 12,
    supplier: 'Mumias Western Distributors',
    location: 'Bay D1',
    status: 'Healthy',
  },
  {
    id: 'prod-06',
    name: 'Bar Soap Sunlight Lemon (Box of 25)',
    sku: 'SOP-SUN-25',
    category: 'Soaps & Detergents',
    purchasePrice: 2400,
    sellingPrice: 2850,
    quantity: 5,
    minStockLevel: 15,
    supplier: 'Unilever Kenya Depot',
    location: 'Bay E2',
    status: 'Critical',
  },
];

export const DEMO_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    name: 'Bidco Africa Ltd Distributor',
    contactPerson: 'Dennis Mutua',
    phone: '+254 722 910 883',
    email: 'orders@bidcodistributors.co.ke',
    productsSupplied: 'Golden Fry, Elianto, Kimbo, Biddy soaps',
    totalPurchased: 1240000,
    balanceOwed: 45000,
    paymentTerms: '14 Days Net',
  },
  {
    id: 'sup-02',
    name: 'Kirinyaga Millers Coop',
    contactPerson: 'Gladys Wambui',
    phone: '+254 711 405 229',
    email: 'mwearice@kirinyagamillers.or.ke',
    productsSupplied: 'Mwea Pishori, Sindano, Fragrant Rice',
    totalPurchased: 890000,
    balanceOwed: 0,
    paymentTerms: 'Cash on Delivery',
  },
  {
    id: 'sup-03',
    name: 'Grain Bulk Millers Nairobi',
    contactPerson: 'Harun Omondi',
    phone: '+254 733 800 122',
    email: 'h.omondi@grainbulk.co.ke',
    productsSupplied: 'Ajab, Pembe, Ndovu Bakers Flour',
    totalPurchased: 650000,
    balanceOwed: 32000,
    paymentTerms: '7 Days Net',
  },
];

export const DEMO_COMPLIANCE_TASKS: ComplianceTask[] = [
  {
    id: 'comp-01',
    title: 'Monthly KRA Value Added Tax (VAT) Return',
    authority: 'KRA',
    dueDate: '2026-10-20',
    daysRemaining: 14,
    status: 'Upcoming',
    description: 'File and pay monthly VAT for September via iTax / eTIMS portal by the 20th day of the following month.',
    actionRequired: 'Reconcile eTIMS sales invoices with input tax purchases before generating payment slip.',
    officialLink: 'https://itax.kra.go.ke',
  },
  {
    id: 'comp-02',
    title: 'PAYE, SHIF (Social Health Authority) & NSSF Remittances',
    authority: 'KRA',
    dueDate: '2026-10-09',
    daysRemaining: 3,
    status: 'Due Soon',
    description: 'Remit statutory payroll deductions for employees (PAYE, SHA/SHIF 2.75%, and NSSF Tier I & II) by the 9th.',
    actionRequired: 'Upload monthly payroll CSV to KRA unified payroll portal and SHA employer portal.',
    officialLink: 'https://sha.go.ke',
  },
  {
    id: 'comp-03',
    title: 'Nairobi City County Single Business Permit Renewal',
    authority: 'County Government',
    dueDate: '2026-12-31',
    daysRemaining: 86,
    status: 'Upcoming',
    description: 'Annual unified business licence & fire inspection certification renewal through NairobiPay.',
    actionRequired: 'Verify trading zone category and clear any outstanding land rates or garbage fees.',
    officialLink: 'https://nairobiservices.go.ke',
  },
  {
    id: 'comp-04',
    title: 'eTIMS Trader Electronic Fiscal Receipt Integration Check',
    authority: 'KRA',
    dueDate: '2026-09-30',
    daysRemaining: 9,
    status: 'Upcoming',
    description: 'KRA requires all businesses to issue valid eTIMS invoices for deductible expense verification.',
    actionRequired: 'Ensure all supplier purchase invoices contain valid KRA control numbers.',
    officialLink: 'https://www.kra.go.ke/en/etims',
  },
];

export const DEMO_NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 'news-01',
    title: 'KRA Streamlines eTIMS for Micro and Small Enterprises with USSD & Online Portal',
    category: 'Tax',
    date: 'September 18, 2026',
    summary: 'The Kenya Revenue Authority has expanded eTIMS Lite accessibility via *222# and web portals, exempting micro-traders below annual threshold from punitive penalties while simplifying input tax claims.',
    source: 'Business Daily Africa',
    sourceUrl: 'https://www.businessdailyafrica.com',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop&q=80',
    whatItMeans: {
      whatHappened: 'KRA introduced lighter eTIMS solutions designed specifically for small dukas, salonists, and traders who do not operate high-end electronic point-of-sale systems.',
      whoIsAffected: 'All Kenyan SMEs selling goods or services to other registered businesses or claiming tax-deductible expenses.',
      whatYouShouldDo: 'Log in to eTIMS Lite or dial *222# to generate electronic fiscal receipts for business clients requesting tax invoices.',
      deadline: 'Immediate implementation across all commercial sales',
      officialSource: 'KRA Public Notice on eTIMS Compliance & SME Support',
    },
  },
  {
    id: 'news-02',
    title: 'Central Bank of Kenya Lowers Benchmark Rate: Commercial Banks Begin Easing SME Credit Terms',
    category: 'Finance',
    date: 'September 15, 2026',
    summary: 'CBK Monetary Policy Committee decision is easing interest rates on unsecured business working capital loans across tier-1 and tier-2 banks.',
    source: 'The Standard Kenya',
    sourceUrl: 'https://www.standardmedia.co.ke',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    whatItMeans: {
      whatHappened: 'The benchmark lending rate reduction provides room for banks to lower borrowing costs on invoice discounting and asset financing.',
      whoIsAffected: 'SME owners carrying commercial overdrafts or planning to finance warehouse expansion or transport vehicles.',
      whatYouShouldDo: 'Review current bank loan interest rates with your relationship manager and explore refinancing options for high-cost debt.',
      officialSource: 'Central Bank of Kenya MPC Communique',
    },
  },
  {
    id: 'news-03',
    title: 'Safaricom and Financial Partners Expand Lipa Na M-Pesa Merchant Credit Facility',
    category: 'Technology',
    date: 'September 10, 2026',
    summary: 'Merchants using Business Till Numbers can now access immediate working capital advances based on 60-day turnover without collateral.',
    source: 'Techweez Kenya',
    sourceUrl: 'https://techweez.com',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop&q=80',
    whatItMeans: {
      whatHappened: 'Automated credit limits for Till and Paybill holders have been increased, with lower daily facility fees for consistent turnover.',
      whoIsAffected: 'Retailers, wholesalers, and food vendors collecting customer payments primarily through Lipa Na M-Pesa.',
      whatYouShouldDo: 'Keep daily sales flowing cleanly through your official Till to build an automated transaction score and qualify for lower facility fees.',
      officialSource: 'Safaricom Merchant Services Notice',
    },
  },
];

export const DEMO_COURSES: TrainingCourse[] = [
  {
    id: 'course-01',
    title: 'Cash Flow Management & M-Pesa Accounting for SMEs',
    category: 'Business Finance',
    level: 'Beginner',
    durationMinutes: 45,
    lessonsCount: 6,
    completedLessons: 6,
    description: 'Learn how to separate personal and business money, calculate true margins after M-Pesa charges, and maintain a 30-day cash buffer.',
    badge: 'Cashflow Master',
  },
  {
    id: 'course-02',
    title: 'eTIMS & Tax Compliance Step-by-Step for Small Traders',
    category: 'Tax & Compliance',
    level: 'Intermediate',
    durationMinutes: 60,
    lessonsCount: 8,
    completedLessons: 5,
    description: 'Demystify VAT, withholding tax, filing Nil returns versus taxable returns, and generating legal electronic fiscal receipts.',
    badge: 'Tax Smart SME',
  },
  {
    id: 'course-03',
    title: 'WhatsApp Business: Converting Inquiries into Paid Orders',
    category: 'WhatsApp Business',
    level: 'Beginner',
    durationMinutes: 40,
    lessonsCount: 5,
    completedLessons: 2,
    description: 'Set up catalog links, automated quick replies, professional broadcast lists, and follow-up templates that convert.',
    badge: 'WhatsApp Sales Pro',
  },
  {
    id: 'course-04',
    title: 'Inventory Control: Eliminating Dead Stock and Pilferage',
    category: 'Operations',
    level: 'Intermediate',
    durationMinutes: 50,
    lessonsCount: 6,
    completedLessons: 0,
    description: 'How to calculate reorder points, conduct weekly stock reconciliations, and handle seasonal demand surges in Kenyan retail.',
    badge: 'Inventory Ace',
    isPremium: true,
  },
];

export const DEMO_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-01',
    title: 'Kenya Youth & Women Enterprise Growth Matching Grant',
    organization: 'Ministry of Cooperatives & MSME Development',
    type: 'Grant',
    amountRange: 'KSh 250,000 - KSh 1,500,000',
    deadline: '2026-10-31',
    eligibility: 'Registered businesses operating for at least 12 months with at least 50% youth or female ownership.',
    location: 'All 47 Counties',
    description: 'Non-repayable matching capital for equipment purchase, cold-storage, packaging machinery, or digitisation.',
    applicationLink: 'https://msme.go.ke/grants',
    isSaved: true,
  },
  {
    id: 'opp-02',
    title: 'Nairobi County MSME Biashara Stimulus Fund',
    organization: 'Nairobi City County Government',
    type: 'Funding',
    amountRange: 'KSh 100,000 - KSh 500,000',
    deadline: '2026-11-15',
    eligibility: 'Holders of valid Nairobi Single Business Permit for 2026 in retail, trade, food, or crafts.',
    location: 'Nairobi County',
    description: 'Low-interest 5% revolving credit fund to support small business working capital and warehouse stocking.',
    applicationLink: 'https://nairobiservices.go.ke/msme',
    isSaved: false,
  },
  {
    id: 'opp-03',
    title: 'Aceli Africa Agri-Food SME Catalytic Loan Facility',
    organization: 'Aceli Africa & Financial Partners',
    type: 'Funding',
    amountRange: 'KSh 1,000,000 - KSh 5,000,000',
    deadline: '2026-12-15',
    eligibility: 'Food distributors, grain aggregation hubs, and agro-processors serving local communities.',
    location: 'Kenya (Nationwide)',
    description: 'De-risked commercial lending with technical assistance grant subsidies for qualifying supply chain businesses.',
    applicationLink: 'https://aceliafrica.org',
    isSaved: true,
  },
];

export const DEMO_WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: 'tpl-01',
    name: 'New Price List & Catalogue',
    category: 'Promotion',
    content: 'Jambo {{customerName}}! Mama Njeri Supplies has updated our wholesale prices for cereals, flours, and cooking oil this week. Check our full price list here: {{link}} or reply to order directly. Karibu sana!',
    variables: ['customerName', 'link'],
  },
  {
    id: 'tpl-02',
    name: 'Payment Reminder (Polite)',
    category: 'Payment Reminder',
    content: 'Habari {{customerName}}, warm greeting from Mama Njeri Supplies. This is a gentle reminder regarding invoice {{invoiceNumber}} for KSh {{amount}} due on {{dueDate}}. You can pay conveniently via M-Pesa Till 892341. Thank you!',
    variables: ['customerName', 'invoiceNumber', 'amount', 'dueDate'],
  },
  {
    id: 'tpl-03',
    name: 'Order Confirmation & Dispatch',
    category: 'Order Confirmation',
    content: 'Habari {{customerName}}! We have received your order for {{items}} worth KSh {{amount}}. Your dispatch is scheduled for delivery today before 2:00 PM. Our driver Peter will call on {{driverPhone}}.',
    variables: ['customerName', 'items', 'amount', 'driverPhone'],
  },
  {
    id: 'tpl-04',
    name: 'Customer Re-engagement',
    category: 'Promotion',
    content: 'Jambo {{customerName}}, we noticed it has been a while since your last restock with us! As a valued partner, we are offering you a special KSh 500 transport voucher on any order over KSh 20,000 this week. Reply YES to claim.',
    variables: ['customerName'],
  },
];

export const DEMO_CONVERSATIONS: WhatsAppConversation[] = [
  {
    id: 'conv-01',
    customerName: 'Kiprono Hotel & Bakery',
    phone: '+254 722 411 902',
    lastMessage: 'Asante sana! We will take 5 more jerrycans tomorrow morning.',
    timestamp: '10:42 AM',
    unreadCount: 1,
    status: 'Open',
    messages: [
      { id: 'm1', sender: 'customer', text: 'Habari Grace, what is the current price for Golden Fry 20L?', time: '09:15 AM' },
      { id: 'm2', sender: 'business', text: 'Jambo bwana Kiprono! Currently at KSh 6,200 per 20L jerrycan with free delivery to town.', time: '09:30 AM' },
      { id: 'm3', sender: 'customer', text: 'Asante sana! We will take 5 more jerrycans tomorrow morning.', time: '10:42 AM' },
    ],
  },
  {
    id: 'conv-02',
    customerName: 'Amina Mini Market',
    phone: '+254 710 882 390',
    lastMessage: 'Order received and verified. Paid via Till.',
    timestamp: 'Yesterday',
    unreadCount: 0,
    status: 'Resolved',
    messages: [
      { id: 'm1', sender: 'business', text: 'Habari Amina, your delivery of Pishori rice is with our driver.', time: 'Yesterday 08:30 AM' },
      { id: 'm2', sender: 'customer', text: 'Order received and verified. Paid via Till.', time: 'Yesterday 09:10 AM' },
    ],
  },
  {
    id: 'conv-03',
    customerName: 'Safari Club Catering',
    phone: '+254 721 445 110',
    lastMessage: 'Our accountant is processing the cheque today.',
    timestamp: 'Sep 19',
    unreadCount: 0,
    status: 'Follow-up Due',
    messages: [
      { id: 'm1', sender: 'business', text: 'Habari Mr. Kamau, following up on invoice INV-2026-0049 for KSh 74,000.', time: 'Sep 19 11:00 AM' },
      { id: 'm2', sender: 'customer', text: 'Our accountant is processing the cheque today.', time: 'Sep 19 02:15 PM' },
    ],
  },
];
